# Generated by Django 6.0 on 2026-01-16 11:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='ID Karyawan')),
                ('phone', models.CharField(max_length=15, verbose_name='No. Telepon')),
                ('address', models.TextField(verbose_name='Alamat')),
                ('position', models.CharField(max_length=100, verbose_name='Jabatan')),
                ('department', models.CharField(default='General', max_length=100, verbose_name='Departemen')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gaji')),
                ('join_date', models.DateField(verbose_name='Tanggal Bergabung')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='Foto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Karyawan',
                'verbose_name_plural': 'Karyawan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('sick', 'Sakit'), ('annual', 'Cuti Tahunan'), ('personal', 'Keperluan Pribadi'), ('marriage', 'Pernikahan'), ('maternity', 'Melahirkan'), ('other', 'Lainnya')], max_length=50, verbose_name='Jenis Izin')),
                ('start_date', models.DateField(verbose_name='Tanggal Mulai')),
                ('end_date', models.DateField(verbose_name='Tanggal Selesai')),
                ('reason', models.TextField(verbose_name='Alasan')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='leave_attachments/', verbose_name='Lampiran')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20, verbose_name='Status')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Catatan Admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leaves', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Permohonan Izin',
                'verbose_name_plural': 'Permohonan Izin',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Tanggal')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='Jam Masuk')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='Jam Keluar')),
                ('status', models.CharField(choices=[('present', 'Hadir'), ('late', 'Terlambat'), ('absent', 'Tidak Hadir'), ('permission', 'Izin'), ('sick', 'Sakit')], default='present', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Lokasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Kehadiran',
                'verbose_name_plural': 'Kehadiran',
                'ordering': ['-date', '-check_in'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='Bulan')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gaji Pokok')),
                ('allowance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tunjangan')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bonus')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Potongan')),
                ('total_salary', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Gaji')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Tanggal Pembayaran')),
                ('notes', models.TextField(blank=True, verbose_name='Catatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_records', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Gaji',
                'verbose_name_plural': 'Gaji',
                'ordering': ['-month'],
                'unique_together': {('employee', 'month')},
            },
        ),
    ]
